select * ,
FIRST_VALUE(TaxRate) OVER (PARTITION BY MONTH(MODIFIEDDATE), YEAR(MODIFIEDDATE) ORDER BY MODIFIEDDATE)FirstTaxRate,
LAST_VALUE(TaxRate) OVER (PARTITION BY MONTH(MODIFIEDDATE), YEAR(MODIFIEDDATE) ORDER BY MODIFIEDDATE )LastTaxRate
FROM Sales.SalesTaxRate
order by ModifiedDate;

----
SELECT 
SalesOrderDetailID,
LineTotal AS CURRENT_TOTAL,
LAG(LINETOTAL) OVER (ORDER BY SalesOrderDetailID) PREVIOUS_LINE_PRICE,
LineTotal - LAG(LINETOTAL) OVER (ORDER BY SalesOrderDetailID) DIFFERENCE_PRICE
FROM Sales.SalesOrderDetail

--DIFFERENCING TWO VALUES

